### ISSUE TITLE
Update instructions about adding a tutorials folder to a project

### ISSUE THREAD

**Issue by heitortsergent** [grafana/writers-toolkit#816]
In the [Tutorials](https://grafana.com/docs/writers-toolkit/structure/topic-types/tutorial/) topic type page, there are a few instructions that I think need to be updated as I was following along to try to add the `tutorials` folder to the k6-docs repository:

- In [Publish your tutorial](https://grafana.com/docs/writers-toolkit/structure/topic-types/tutorial/#publish-your-tutorial) the instructions says to create a tutorial page under `docs/sources`, but it should be under `docs/sources/<VERSION>`.
- In [Before you begin](https://grafana.com/docs/writers-toolkit/structure/topic-types/tutorial/#before-you-begin), the instructions show a code snippet with some front matter properties. In the k6-docs case, we didn't have multiple targets in that part of the front matter, so when I copy+pasted that snippet, the build stopped working. It would be nice to have a longer snippet, maybe:

```
cascade:
  - _target:
      path: /docs/<PROJECT>/*/tutorials/**
    _build:
      list: false
      render: false
  - _target:
      path: /docs/<PROJECT>/**
      ...
```
